version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  api:
    depends_on:
      - "postgres_image"
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${MODE}
      DB_CONNECTION_STRING: Server=postgres_image;Port=5432;Username=postgres;Password=${DB_PASSWORD};Database=postgres
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - dockerapi-dev
  postgres_image:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - dockerapi-dev
volumes:
  db_volume:
